Add subgroup option.
stormcat24/protodep pull request #69
Opened 2021-06-11 00:44 UTC by rcgoodfellow

In GitLab it's possible to have subgroups to organize repositories. Protodep can not currently deal with this as it assumes the repo path follows GitHub rules and only contains `github.com/$organization/$repo`.

This commit adds a subgroup property to the dependency schema that allows the user to specify the subgroup or subgroups that are involved in the git URL reference. When the subgroup property is not present, the behavior remains unchanged so this should not be a breaking change.

As a concrete example consider this repo

https://gitlab.com/mergetb/portal/services

that has the structure `https://gitlab.com/$group/$subgroup/$repo`, in general arbitrary subgrouping on GitLab is possible 
 `https://gitlab.com/$gropup/$a/$b/$c/.../$repo`.

Thanks for the very useful tool!

2021-06-11 04:58 UTC, stormcat24 commented
Thank you for using protodep. Please wait a few days for review 🙏

2021-06-21 08:48 UTC, stormcat24 requested changes
@rcgoodfellow
Sorry for the late review. Thank you for your contribution.

Can you make two request changes?

2021-06-21 08:48 UTC, stormcat24 commented on dependency/schema.go
> +	subgroupTokens := strings.Split(d.Subgroup, "/")
If `Subgroup` is empty string, `strings.Split` returns `1` in Go language.
This behavior causes an error in the existing settings.

```go
subgroupTokens := make([]string, 0)
if d.Subgroup != "" {
    subgroupTokens = strings.Split(d.Subgroup, "/")
}
```

2021-08-17 19:24 UTC, sf-jassmith commented
@rcgoodfellow Great Fix! I am also using gitlab.  Any chance you could make the suggested changes and get this merged soon?

2021-08-21 01:15 UTC, rcgoodfellow commented
Requested changes have been made. Sorry for the delay.

2021-08-21 06:31 UTC, stormcat24 approved these changes

2021-08-21 06:32 UTC, merged

2021-08-21 06:43 UTC, stormcat24 commented
@rcgoodfellow Awesome works! Thanks!
This feature has released in [0.1.5](https://github.com/stormcat24/protodep/releases/tag/0.1.5)

@sf-jassmith Please use this version!